spring:
  sql.init.mode: always
  h2.console.enabled: true
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:./target/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: